/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.bioskopapp.client;

import com.uas.bioskopapp.client.kelas.Bangku;
import com.uas.bioskopapp.client.kelas.Booking;
import com.uas.bioskopapp.client.kelas.Pesan;
import com.uas.bioskopapp.connect.Konek;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Pemesanan extends javax.swing.JFrame {

    private String username, pass;
    private Statement ks;
    private ResultSet Rslogin;
    private String sql="";
    private Connection koneksi;
    private Statement cs;
    private Konek kdb = new Konek();
    
    
    public boolean bioskopDipilih = false;
    public boolean filmDipilih = false;
    public String baris, nomer;
    public int[] bangku = new int[12];
    /**
     * Creates new form Pemesanan
     */
    public Pemesanan() {
        initComponents();
 
        ShowComboDB();
    }

     private void ShowComboDB(){
        DefaultComboBoxModel data = new DefaultComboBoxModel();
        DefaultComboBoxModel data2 = new DefaultComboBoxModel();
       
        bioskopComboBox.setModel(data);
       
        try{
            Booking bk = new Booking();
            bk.comboDataBioskop(data);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    void namauser(String nama, String password) {            
            
            try {
            sql = "select * from pelanggan where username='"+nama+"'"
            + "and pass='"+password+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rslogin = cs.executeQuery(sql);
            if(Rslogin.next()){
            naPesTf.setText(Rslogin.getString("nama"));
            username=Rslogin.getString("username");
            pass=Rslogin.getString("pass");

            }else{
                System.out.println("Tidak ada username");
            }
            } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
                           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bangkuA1 = new javax.swing.JButton();
        bangkuA2 = new javax.swing.JButton();
        bangkuA3 = new javax.swing.JButton();
        bangkuA4 = new javax.swing.JButton();
        bangkuB1 = new javax.swing.JButton();
        bangkuC1 = new javax.swing.JButton();
        bangkuB2 = new javax.swing.JButton();
        bangkuC2 = new javax.swing.JButton();
        bangkuB3 = new javax.swing.JButton();
        bangkuB4 = new javax.swing.JButton();
        bangkuC3 = new javax.swing.JButton();
        bangkuC4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        naPesTf = new javax.swing.JTextField();
        bioskopComboBox = new javax.swing.JComboBox<>();
        filmComboBox = new javax.swing.JComboBox<>();
        studioL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pesanBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        judulL = new javax.swing.JLabel();
        genL = new javax.swing.JLabel();
        durL = new javax.swing.JLabel();
        tglL = new javax.swing.JLabel();
        jamL = new javax.swing.JLabel();
        hrgL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bayarTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking Tiket");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pemesan :");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        bangkuA1.setBackground(new java.awt.Color(255, 0, 0));
        bangkuA1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuA1.setForeground(new java.awt.Color(255, 255, 255));
        bangkuA1.setText("A1");
        bangkuA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA1ActionPerformed(evt);
            }
        });

        bangkuA2.setBackground(new java.awt.Color(255, 0, 0));
        bangkuA2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuA2.setForeground(new java.awt.Color(255, 255, 255));
        bangkuA2.setText("A2");
        bangkuA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA2ActionPerformed(evt);
            }
        });

        bangkuA3.setBackground(new java.awt.Color(255, 0, 0));
        bangkuA3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuA3.setForeground(new java.awt.Color(255, 255, 255));
        bangkuA3.setText("A3");
        bangkuA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA3ActionPerformed(evt);
            }
        });

        bangkuA4.setBackground(new java.awt.Color(255, 0, 0));
        bangkuA4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuA4.setForeground(new java.awt.Color(255, 255, 255));
        bangkuA4.setText("A4");
        bangkuA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA4ActionPerformed(evt);
            }
        });

        bangkuB1.setBackground(new java.awt.Color(255, 0, 0));
        bangkuB1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuB1.setForeground(new java.awt.Color(255, 255, 255));
        bangkuB1.setText("B1");
        bangkuB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB1ActionPerformed(evt);
            }
        });

        bangkuC1.setBackground(new java.awt.Color(255, 0, 0));
        bangkuC1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuC1.setForeground(new java.awt.Color(255, 255, 255));
        bangkuC1.setText("C1");
        bangkuC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC1ActionPerformed(evt);
            }
        });

        bangkuB2.setBackground(new java.awt.Color(255, 0, 0));
        bangkuB2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuB2.setForeground(new java.awt.Color(255, 255, 255));
        bangkuB2.setText("B2");
        bangkuB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB2ActionPerformed(evt);
            }
        });

        bangkuC2.setBackground(new java.awt.Color(255, 0, 0));
        bangkuC2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuC2.setForeground(new java.awt.Color(255, 255, 255));
        bangkuC2.setText("C2");
        bangkuC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC2ActionPerformed(evt);
            }
        });

        bangkuB3.setBackground(new java.awt.Color(255, 0, 0));
        bangkuB3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuB3.setForeground(new java.awt.Color(255, 255, 255));
        bangkuB3.setText("B3");
        bangkuB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB3ActionPerformed(evt);
            }
        });

        bangkuB4.setBackground(new java.awt.Color(255, 0, 0));
        bangkuB4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuB4.setForeground(new java.awt.Color(255, 255, 255));
        bangkuB4.setText("B4");
        bangkuB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB4ActionPerformed(evt);
            }
        });

        bangkuC3.setBackground(new java.awt.Color(255, 0, 0));
        bangkuC3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuC3.setForeground(new java.awt.Color(255, 255, 255));
        bangkuC3.setText("C3");
        bangkuC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC3ActionPerformed(evt);
            }
        });

        bangkuC4.setBackground(new java.awt.Color(255, 0, 0));
        bangkuC4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bangkuC4.setForeground(new java.awt.Color(255, 255, 255));
        bangkuC4.setText("C4");
        bangkuC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Layar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel9)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bangkuA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bangkuA2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bangkuB1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bangkuC1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bangkuB2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bangkuC2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bangkuA3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bangkuA4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bangkuB3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bangkuC3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bangkuB4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bangkuC4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bangkuA1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bangkuB4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuB3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bangkuB1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuB2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bangkuC2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuC1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuC3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuC4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bioskop :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Film :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Studio :");

        bioskopComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bioskopComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bioskopComboBoxItemStateChanged(evt);
            }
        });
        bioskopComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bioskopComboBoxMouseClicked(evt);
            }
        });
        bioskopComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskopComboBoxActionPerformed(evt);
            }
        });

        filmComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Film--" }));
        filmComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filmComboBoxItemStateChanged(evt);
            }
        });
        filmComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmComboBoxMouseClicked(evt);
            }
        });

        studioL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studioL.setForeground(new java.awt.Color(255, 255, 255));
        studioL.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pilih Tempat Duduk :");

        pesanBtn.setText("Pesan");
        pesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Film :");

        jLabel10.setText("Genre       :");

        jLabel11.setText("Tanggal    :");

        jLabel12.setText("Durasi       :");

        jLabel13.setText("Jam          :");

        jLabel15.setText("Harga       :");

        judulL.setText("-");

        genL.setText("-");

        durL.setText("-");

        tglL.setText("-");

        jamL.setText("-");

        hrgL.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(judulL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(durL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jamL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hrgL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(judulL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(durL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tglL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jamL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(hrgL))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bayar   :");

        bayarTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarTfActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Detail Film :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(naPesTf)
                            .addComponent(bioskopComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studioL)
                            .addComponent(bayarTf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pesanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(naPesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bioskopComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(filmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(studioL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(bayarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bayarTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarTfActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.namauser(username, pass);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void bioskopComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bioskopComboBoxItemStateChanged
        // TODO add your handling code here:
        if(bioskopDipilih){
            DefaultComboBoxModel spesFilm = new DefaultComboBoxModel();
            filmComboBox.setModel(spesFilm);
            try{
                Booking bk = new Booking();
                if(bioskopComboBox.getSelectedItem()=="--Pilih Bioskop--"){
                
                judulL.setText("-");
                genL.setText("-");
                durL.setText("-");
                tglL.setText("-");
                jamL.setText("-");
                hrgL.setText("-");
                }else{
                bk.insertFilmComboBox(spesFilm, bioskopComboBox.getSelectedItem().toString());
                bk.getStudio(studioL, bioskopComboBox.getSelectedItem().toString(), filmComboBox.getSelectedItem().toString());
                }
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
            bioskopDipilih = false;
        }
    }//GEN-LAST:event_bioskopComboBoxItemStateChanged

    private void bioskopComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioskopComboBoxMouseClicked
        // TODO add your handling code here:
        bioskopDipilih = true;
    }//GEN-LAST:event_bioskopComboBoxMouseClicked

    private void filmComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmComboBoxMouseClicked
        // TODO add your handling code here:
        filmDipilih = true;
    }//GEN-LAST:event_filmComboBoxMouseClicked

    private void setBangku(int[] arrayBangku,int index, JButton tombolBangku){
        if(arrayBangku[index] == 0){
            tombolBangku.setEnabled(true);
        }else{
            tombolBangku.setEnabled(false);
        }
    }
    
    private void filmComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filmComboBoxItemStateChanged
        // TODO add your handling code here:
        if(filmDipilih){
            try{
                Booking bk = new Booking();
                if(filmComboBox.getSelectedItem()=="--Pilih Film--"){
                studioL.setText("0");
                judulL.setText("-");
                genL.setText("-");
                durL.setText("-");
                tglL.setText("-");
                jamL.setText("-");
                hrgL.setText("-");
                }else{
                bk.getStudio(studioL, bioskopComboBox.getSelectedItem().toString(), filmComboBox.getSelectedItem().toString());
                bk.getDataFilm(judulL,genL,durL,tglL,jamL,hrgL,bioskopComboBox.getSelectedItem().toString(), filmComboBox.getSelectedItem().toString());

                Bangku ba = new Bangku();
                ba.getDataBangku(studioL.getText(), bioskopComboBox.getSelectedItem().toString(), bangku);
                
                setBangku(bangku,0,bangkuA1);
                setBangku(bangku,1,bangkuA2);
                setBangku(bangku,2,bangkuA3);
                setBangku(bangku,3,bangkuA4);                
                setBangku(bangku,4,bangkuB1);
                setBangku(bangku,5,bangkuB2);
                setBangku(bangku,6,bangkuB3);
                setBangku(bangku,7,bangkuB4);               
                setBangku(bangku,8,bangkuC1);
                setBangku(bangku,9,bangkuC2);
                setBangku(bangku,10,bangkuC3);
                setBangku(bangku,11,bangkuC4);

            }
               
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            filmDipilih = false;
        }
    }//GEN-LAST:event_filmComboBoxItemStateChanged

    private void bangkuA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA1ActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "1";
    }//GEN-LAST:event_bangkuA1ActionPerformed

    private void bangkuA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA2ActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "2";
    }//GEN-LAST:event_bangkuA2ActionPerformed

    private void bangkuA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA3ActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "3";
    }//GEN-LAST:event_bangkuA3ActionPerformed

    private void bangkuA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA4ActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "4";
    }//GEN-LAST:event_bangkuA4ActionPerformed

    private void bangkuB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB1ActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "1";
    }//GEN-LAST:event_bangkuB1ActionPerformed

    private void bangkuB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB2ActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "2";
    }//GEN-LAST:event_bangkuB2ActionPerformed

    private void bangkuB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB3ActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "3";
    }//GEN-LAST:event_bangkuB3ActionPerformed

    private void bangkuB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB4ActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "4";
    }//GEN-LAST:event_bangkuB4ActionPerformed

    private void bangkuC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC1ActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "1";
    }//GEN-LAST:event_bangkuC1ActionPerformed

    private void bangkuC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC2ActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "2";
    }//GEN-LAST:event_bangkuC2ActionPerformed

    private void bangkuC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC3ActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "3";
    }//GEN-LAST:event_bangkuC3ActionPerformed

    private void bangkuC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC4ActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "4";
    }//GEN-LAST:event_bangkuC4ActionPerformed

    private void pesanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanBtnActionPerformed
        // TODO add your handling code here:
        
         if("".equals(naPesTf.getText())){
                JOptionPane.showMessageDialog(null, "Harap Masukkan Nama Pemesan", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if("--Pilih Bioskop--".equals(bioskopComboBox.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null, "Harap Memilih Bioskop", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if("--Pilih Film--".equals(filmComboBox.getSelectedItem().toString()) || "".equals(filmComboBox.getSelectedItem().toString()) ){
                JOptionPane.showMessageDialog(null, "Harap Memilih Film", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if("".equals(bayarTf.getText())){
                JOptionPane.showMessageDialog(null, "Harap Membayar", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if(bayarTf.getText().matches("[0-9]+") == false){
                JOptionPane.showMessageDialog(null, "Harap Memasukkan Nominal Pembayaran", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if(Integer.parseInt(bayarTf.getText()) > Integer.parseInt(hrgL.getText()) ||Integer.parseInt(bayarTf.getText()) < Integer.parseInt(hrgL.getText()) ){
                JOptionPane.showMessageDialog(null, "Harap Membayar Sesuai Harga", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else if(baris==null||nomer==null){
                JOptionPane.showMessageDialog(null, "Harap Memilih Bangku Tempat Duduk", "Status", JOptionPane.ERROR_MESSAGE, null);
            }else{
             try {
           
            Pesan CP  = new Pesan(username, bioskopComboBox.getSelectedItem().toString(), filmComboBox.getSelectedItem().toString(), studioL.getText(), tglL.getText(), jamL.getText(), naPesTf.getText(), baris, nomer, hrgL.getText());
            if (CP.masukkanData()) {
                JOptionPane.showMessageDialog(null, ""+bioskopComboBox.getSelectedItem().toString()+""
                        + "\n"
                        + "\n--------------------------------------"
                        + "\n"
                        + "\nJudul : " + filmComboBox.getSelectedItem().toString()
                        + "\nTanggal : " + tglL.getText()
                        + "\nWaktu : " + jamL.getText()
                        + "\nBaris : " + baris + " Nomor : " + nomer + ""
                        + "\nHarga : " + hrgL.getText()
                        + "\nStudio : " + studioL.getText()
                        + "\nNama Pemesan : " + naPesTf.getText()
                        + "", "Status", JOptionPane.INFORMATION_MESSAGE, null);
                System.out.println("Berhasil");
                
                Bangku ba = new Bangku();
                String bangkuNya = baris + nomer;
                ba.setBangku(studioL.getText(), bioskopComboBox.getSelectedItem().toString(), bangkuNya);
                

                ba.getDataBangku(studioL.getText(), bioskopComboBox.getSelectedItem().toString(), bangku);
                
                setBangku(bangku,0,bangkuA1);
                setBangku(bangku,1,bangkuA2);
                setBangku(bangku,2,bangkuA3);
                setBangku(bangku,3,bangkuA4);
                
                setBangku(bangku,4,bangkuB1);
                setBangku(bangku,5,bangkuB2);
                setBangku(bangku,6,bangkuB3);
                setBangku(bangku,7,bangkuB4);
                
                setBangku(bangku,8,bangkuC1);
                setBangku(bangku,9,bangkuC2);
                setBangku(bangku,10,bangkuC3);
                setBangku(bangku,11,bangkuC4);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal", "Status", JOptionPane.ERROR_MESSAGE, null);
            }
        } catch (SQLException ex) {
            
        }
        }
        
    }//GEN-LAST:event_pesanBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        naPesTf.setText("");
        bioskopComboBox.setSelectedIndex(0);
        filmComboBox.setSelectedIndex(0);
        baris="";
        nomer="";
        bayarTf.setText("");
        studioL.setText("0");
        judulL.setText("-");
        genL.setText("-");
        durL.setText("-");
        tglL.setText("-");
        jamL.setText("-");
        hrgL.setText("-");
        
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void bioskopComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskopComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bioskopComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bangkuA1;
    private javax.swing.JButton bangkuA2;
    private javax.swing.JButton bangkuA3;
    private javax.swing.JButton bangkuA4;
    private javax.swing.JButton bangkuB1;
    private javax.swing.JButton bangkuB2;
    private javax.swing.JButton bangkuB3;
    private javax.swing.JButton bangkuB4;
    private javax.swing.JButton bangkuC1;
    private javax.swing.JButton bangkuC2;
    private javax.swing.JButton bangkuC3;
    private javax.swing.JButton bangkuC4;
    private javax.swing.JTextField bayarTf;
    private javax.swing.JComboBox<String> bioskopComboBox;
    private javax.swing.JLabel durL;
    private javax.swing.JComboBox<String> filmComboBox;
    private javax.swing.JLabel genL;
    private javax.swing.JLabel hrgL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jamL;
    private javax.swing.JLabel judulL;
    private javax.swing.JTextField naPesTf;
    private javax.swing.JButton pesanBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel studioL;
    private javax.swing.JLabel tglL;
    // End of variables declaration//GEN-END:variables
}
